import { route, index } from '@react-router/dev/routes';

export default [
  index('./page.jsx'),
  route('dashboard', './dashboard/page.jsx'),
  route('login', './login/page.jsx'),
  route('signup', './signup/page.jsx'),
  route('howitworks', './howitworks/page.jsx'),
  route('settings', './settings/page.jsx'),
  route('profile', './profile/page.jsx'),
  route('api/auth/me', './api/auth/me/route.js'),
  route('api/auth/circle/device', './api/auth/circle/device/route.js'),
  route('api/auth/circle/login', './api/auth/circle/login/route.js'),
  route('api/auth/circle/register', './api/auth/circle/register/route.js'),
  route('api/auth/circle/complete', './api/auth/circle/complete/route.js'),
  route('api/auth/circle/session', './api/auth/circle/session/route.js'),
  route('api/tips/history', './api/tips/history/route.js'),
  route('api/tips/analytics', './api/tips/analytics/route.js'),
  route('api/tips/prepare', './api/tips/prepare/route.js'),
  route('api/tips/confirm', './api/tips/confirm/route.js'),
  route('api/tips/escrow', './api/tips/escrow/route.js'),
  route('api/cron/index-tips', './api/cron/index-tips/route.js'),
  route('api/user/check-username', './api/user/check-username/route.js'),
  route('api/user/fee-mode', './api/user/fee-mode/route.js'),
  route('api/user/preferences', './api/user/preferences/route.js'),
  route('api/reports', './api/reports/route.js'),
  route('api/reputation/export', './api/reputation/export/route.js'),
  route('api/user/profile', './api/user/profile/route.js'),
  route('api/user/:username', './api/user/[username]/route.js'),
  route('api/wallet/balance', './api/wallet/balance/route.js'),
  route('api/wallet/withdraw', './api/wallet/withdraw/route.js'),
  route('api/wallet/withdrawals', './api/wallet/withdrawals/route.js'),
  route('api/events', './api/events/route.js'),
  route('api/wallet/transactions', './api/wallet/transactions/route.js'),
  route('api/autosave/enable', './api/autosave/enable/route.js'),
  route('api/autosave/confirm', './api/autosave/confirm/route.js'),
  route('api/autosave/state', './api/autosave/state/route.js'),
  route('api/autosave/disable', './api/autosave/disable/route.js'),
  route('api/autosave/confirm-disable', './api/autosave/confirm-disable/route.js'),
  route('api/tipsplit/state', './api/tipsplit/state/route.js'),
  route('api/tipsplit/save', './api/tipsplit/save/route.js'),
  route('api/livestream/toggle', './api/livestream/toggle/route.js'),
  // Must sit last before the catch-all: every fixed route wins over a
  // username, and reserved_handles blocks anyone claiming one.
  route(':username', './tip/[username]/page.jsx', { id: 'username-short' }),
  route('*', './__create/not-found.tsx'),
];
