import { route, index } from '@react-router/dev/routes';

export default [
  index('./page.jsx'),
  route('dashboard', './dashboard/page.jsx'),
  route('login', './login/page.jsx'),
  route('signup', './signup/page.jsx'),
  route('forgot-password', './forgot-password/page.jsx'),
  route('howitworks', './howitworks/page.jsx'),
  route('settings', './settings/page.jsx'),
  route('profile', './profile/page.jsx'),
  route('tip/:username', './tip/[username]/page.jsx'),
  route('api/auth/signup', './api/auth/signup/route.js'),
  route('api/auth/login', './api/auth/login/route.js'),
  route('api/auth/me', './api/auth/me/route.js'),
  route('api/auth/reset-password', './api/auth/reset-password/route.js'),
  route('api/auth/request-password-reset', './api/auth/request-password-reset/route.js'),
  route('api/auth/verify-password', './api/auth/verify-password/route.js'),
  route('api/auth/circle/device', './api/auth/circle/device/route.js'),
  route('api/auth/circle/login', './api/auth/circle/login/route.js'),
  route('api/auth/circle/register', './api/auth/circle/register/route.js'),
  route('api/auth/circle/complete', './api/auth/circle/complete/route.js'),
  route('api/auth/circle/status', './api/auth/circle/status/route.js'),
  route('api/auth/circle/session', './api/auth/circle/session/route.js'),
  route('api/tips/history', './api/tips/history/route.js'),
  route('api/tips/analytics', './api/tips/analytics/route.js'),
  route('api/tips/record', './api/tips/record/route.js'),
  route('api/tips/prepare', './api/tips/prepare/route.js'),
  route('api/tips/confirm', './api/tips/confirm/route.js'),
  route('api/tips/escrow', './api/tips/escrow/route.js'),
  route('api/cron/index-tips', './api/cron/index-tips/route.js'),
  route('api/tips/sponsored', './api/tips/sponsored/route.js'),
  route('api/user/check-username', './api/user/check-username/route.js'),
  route('api/user/fee-mode', './api/user/fee-mode/route.js'),
  route('api/user/preferences', './api/user/preferences/route.js'),
  route('api/reports', './api/reports/route.js'),
  route('api/reputation/export', './api/reputation/export/route.js'),
  route('api/user/profile', './api/user/profile/route.js'),
  route('api/user/:username', './api/user/[username]/route.js'),
  route('api/wallet/balance', './api/wallet/balance/route.js'),
  route('api/wallet/withdraw', './api/wallet/withdraw/route.js'),
  route('api/wallet/transactions', './api/wallet/transactions/route.js'),
  // Must sit last before the catch-all: every fixed route wins over a
  // username, and reserved_handles blocks anyone claiming one.
  route(':username', './tip/[username]/page.jsx', { id: 'username-short' }),
  route('*', './__create/not-found.tsx'),
];
